### ISSUE TITLE
Game is crashing

### ISSUE THREAD

**Issue by sternschnaube** [CodeF53/ChatWalk#1]
https://pastebin.com/raw/kh6Uv0QF

**Comment by CodeF53** [comment]
Looks like what normally happens in a mixin conflict.

What mods are you using?

**Comment by venaminecraft** [comment]
Currently:

![image](https://user-images.githubusercontent.com/120551916/211155493-3dbd0784-1be9-4eca-bb20-e00f7f54cd84.png)

**Comment by CodeF53** [comment]
I think this may be a conflict between Cardinal Ice Boats and Chat Walk because they have the same functionality. (except cardinal ice boats is limited to only when you're in a boat)

I just need to set mixin priorities to fix this.

**Comment by CodeF53** [comment]
Giving the mixins priorities doesn't seem to be working, this may take a bit, sorry.

You could temporarily fix this by downgrading CardinalIceBoats to 1.2.4.1 - 1.19.3

**Comment by CodeF53** [comment]
Fixed in 1.0.1, with commit 6ed1e43973f71b69976bf360b58cd53d37f59c4d and Cardinal Ice Boats 1.3.1 commit [0a14b72](0a14b72ee9b6d40ef1c6b21aa9840f365d3e3855)

Make sure to update both ChatWalk and Cardinal Ice Boats at the same time!

https://modrinth.com/mod/chatwalk/version/1.19-1.0.1
https://modrinth.com/mod/cardinalboats/version/1.3.1-1.19.3

**Comment by venaminecraft** [comment]
Super fast problem spotting and fixing - thank you 😊
